DetectionResult(
    detections=[
        Detection(
            bounding_box=BoundingBox(origin_x=340, 
                                     origin_y=145, 
                                     width=169, 
                                     height=172),
             categories=[Category(
                 index=None,
                 score=0.7437631487846375, 
                 display_name=None, 
                 category_name='cat')],
               keypoints=[]),
        Detection(
            bounding_box=BoundingBox(
                origin_x=0, 
                origin_y=96, 
                width=211, 
                height=222),
                categories=[Category(
                    index=None, 
                    score=0.6384729146957397, 
                    display_name=None, 
                    category_name='horse')], 
                keypoints=[])])